import {fireEvent, render, screen} from '@testing-library/react';
import {describe, expect, it, vi} from 'vitest';
import type {DemoBundle, Event} from '../types/demo';
import {MissionControl} from './MissionControl';
import {JudgeMode} from './JudgeMode';
import {TemporalTimeline} from './TemporalTimeline';
import {HistoryComparison} from './HistoryComparison';
import {TargetCoveragePanel} from './TargetCoveragePanel';
import {ReasoningReceipt} from './ReasoningReceipt';
import {TechnicalDrawer} from './TechnicalDrawer';

const event: Event = {event_id: 'evt-1', sequence: 1, event_type: 'COMMAND_EXECUTED', summary: 'Run representative evaluation', command: 'pytest', status: 'SUCCEEDED', output_preview: 'passed', command_tags: ['evaluation']};
const bundle: DemoBundle = {bundle_schema_version: '1', demo_id: 'demo-1', title: 'Demo', artifacts: {
  trajectory: {run_id: 'run-1', scenario_id: 'scenario', trajectory_hash: 'baseline-hash', events: [event]}, replay_trajectory: {trajectory_hash: 'replay-hash', events: [{...event, event_id: 'evt-r'}]}, intervention: {clue: 'Verify on a representative labeled query set.', intervention_id: 'int-1', intervention_hash: 'int-hash'},
  divergence: {divergence_id: 'div-1', divergence_hash: 'div-hash', event_differences: [{difference_id: 'diff-1', difference_type: 'REPLAY_ONLY', summary: 'Replay evaluates', baseline_event_ids: [], replay_event_ids: ['evt-r']}], first_structural_divergence: {summary: 'A difference', replay_event_id: 'evt-r'}},
  counterfactual: {coverage_id: 'coverage-1', coverage_hash: 'coverage-hash', policy_version: '1.0', target_coverages: [{target_id: 'representative-labeled-evaluation', baseline_verdict: 'MISSED', replay_coverage_status: 'OBSERVED', coverage_proof: {observed_stages: ['fixture', 'evaluation'], missing_stages: []}, limitations: ['Coverage is not correctness.']}], shift: {status: 'TARGET_COVERAGE_INCREASED', target_level_shifts: [{direction: 'INCREASED'}]}, activity_volume_context: {total_activity_status: 'LESS_TOTAL_ACTIVITY', target_coverage_relationship: 'INCREASED_TARGET_COVERAGE', statement: 'The replay contained less total observable evaluation activity while increasing coverage of the specific representative-evaluation target.'}},
  assessment: {assessment_id: 'assessment-1', assessment_hash: 'assessment-hash', decision_under_evaluation: 'Production default', overall_finding: {statement: 'Representative evaluation was absent.'}}, evaluation: {}, phase_8_receipt: {manifest_sha256: 'receipt-hash', source_lineage_hash: 'lineage-hash'}, replay_manifest: {replay_id: 'replay-1', provider: 'fake', provider_version: '1.0', live_model_invoked: false},
}};

describe('demo interface evidence views', () => {
  it('renders mission control', () => { render(<MissionControl bundle={bundle} onGuided={vi.fn()} onExplore={vi.fn()} />); expect(screen.getByText(/Git remembers/)).toBeInTheDocument(); });
  it('exposes guided-demo action', () => { const action = vi.fn(); render(<MissionControl bundle={bundle} onGuided={action} onExplore={vi.fn()} />); fireEvent.click(screen.getByText('Launch Guided Demo')); expect(action).toHaveBeenCalled(); });
  it('renders all eight judge steps', () => { render(<JudgeMode bundle={bundle} step={0} setStep={vi.fn()} onExit={vi.fn()} />); expect(screen.getByText('Original decision')).toBeInTheDocument(); expect(screen.getByText(/STEP 1 OF 8/)).toBeInTheDocument(); });
  it('supports judge keyboard navigation', () => { const setStep = vi.fn(); render(<JudgeMode bundle={bundle} step={0} setStep={setStep} onExit={vi.fn()} />); fireEvent.keyDown(window, {key: 'ArrowRight'}); expect(setStep).toHaveBeenCalledWith(1); });
  it('renders timeline controls', () => { render(<TemporalTimeline baseline={[event]} replay={[]} cursor={0} setCursor={vi.fn()} playing={false} setPlaying={vi.fn()} speed={1} setSpeed={vi.fn()} enabled={new Set(['evaluation'])} setEnabled={vi.fn()} />); expect(screen.getByLabelText('Play timeline')).toBeInTheDocument(); });
  it('plays and pauses the timeline', () => { const setPlaying = vi.fn(); const view = render(<TemporalTimeline baseline={[event]} replay={[]} cursor={0} setCursor={vi.fn()} playing={false} setPlaying={setPlaying} speed={1} setSpeed={vi.fn()} enabled={new Set(['evaluation'])} setEnabled={vi.fn()} />); fireEvent.click(screen.getByLabelText('Play timeline')); expect(setPlaying).toHaveBeenCalledWith(true); view.rerender(<TemporalTimeline baseline={[event]} replay={[]} cursor={0} setCursor={vi.fn()} playing setPlaying={setPlaying} speed={1} setSpeed={vi.fn()} enabled={new Set(['evaluation'])} setEnabled={vi.fn()} />); expect(screen.getByLabelText('Pause timeline')).toBeInTheDocument(); });
  it('moves to next timeline event', () => { const setCursor = vi.fn(); render(<TemporalTimeline baseline={[event, {...event, event_id: 'evt-2'}]} replay={[]} cursor={0} setCursor={setCursor} playing={false} setPlaying={vi.fn()} speed={1} setSpeed={vi.fn()} enabled={new Set(['evaluation'])} setEnabled={vi.fn()} />); fireEvent.click(screen.getByLabelText('Next event')); expect(setCursor).toHaveBeenCalledWith(1); });
  it('filters timeline categories', () => { const setEnabled = vi.fn(); render(<TemporalTimeline baseline={[event]} replay={[]} cursor={0} setCursor={vi.fn()} playing={false} setPlaying={vi.fn()} speed={1} setSpeed={vi.fn()} enabled={new Set(['evaluation'])} setEnabled={setEnabled} />); fireEvent.click(screen.getByLabelText('evaluation')); expect(setEnabled).toHaveBeenCalled(); });
  it('shows empty timeline evidence honestly', () => { render(<TemporalTimeline baseline={[]} replay={[]} cursor={0} setCursor={vi.fn()} playing={false} setPlaying={vi.fn()} speed={1} setSpeed={vi.fn()} enabled={new Set()} setEnabled={vi.fn()} />); expect(screen.getByText(/No timeline events/)).toBeInTheDocument(); });
  it('renders aligned split-screen differences', () => { render(<HistoryComparison artifact={bundle.artifacts.divergence} />); expect(screen.getByText('BASELINE HISTORY')).toBeInTheDocument(); expect(screen.getByText('COUNTERFACTUAL REPLAY')).toBeInTheDocument(); });
  it('renders accepted target coverage values', () => { render(<TargetCoveragePanel artifact={bundle.artifacts.counterfactual} />); expect(screen.getByText('MISSED')).toBeInTheDocument(); expect(screen.getByText('OBSERVED')).toBeInTheDocument(); });
  it('keeps total activity distinct from target coverage', () => { render(<TargetCoveragePanel artifact={bundle.artifacts.counterfactual} />); expect(screen.getByText('LESS_TOTAL_ACTIVITY')).toBeInTheDocument(); expect(screen.getByText('INCREASED_TARGET_COVERAGE')).toBeInTheDocument(); });
  it('states that live model invocation is false in the receipt', () => { render(<ReasoningReceipt bundle={bundle} />); expect(screen.getByText('false')).toBeInTheDocument(); });
  it('shows receipt copy feedback', async () => { Object.assign(navigator, {clipboard: {writeText: vi.fn().mockResolvedValue(undefined)}}); render(<ReasoningReceipt bundle={bundle} />); fireEvent.click(screen.getByText('Copy receipt')); expect(await screen.findByText('Receipt copied')).toBeInTheDocument(); });
  it('offers a receipt download action', () => { render(<ReasoningReceipt bundle={bundle} />); expect(screen.getByText('Download JSON')).toBeInTheDocument(); });
  it('keeps technical evidence hidden until drawer is opened', () => { const view = render(<TechnicalDrawer bundle={bundle} open={false} onClose={vi.fn()} />); expect(view.container).toBeEmptyDOMElement(); view.rerender(<TechnicalDrawer bundle={bundle} open onClose={vi.fn()} />); expect(screen.getByLabelText('Technical evidence drawer')).toBeInTheDocument(); });
  it('does not make correctness or causality claims', () => { render(<TargetCoveragePanel artifact={bundle.artifacts.counterfactual} />); expect(screen.queryByText(/retrieval quality improved/i)).not.toBeInTheDocument(); expect(screen.queryByText(/caused the change/i)).not.toBeInTheDocument(); });
});
